//localstorage

export default [
  {
    id: 0,
    sentenceBosnian: "Zdravo, kako ste?",
    firstWord: "Zdravo, ",
    secondWord: "kako",
    thirdWord: "ste?",
    fourthWord: "",
    ENG_firstWord: "Hello,",
    ENG_secondWord: "how",
    ENG_thirdWord: "are",
    ENG_fourthword: "you?",
    choices: ["when", "how", "where", "what"],
    correctAnswer: "how",
  },
  {
    id: 1,
    sentenceBosnian: "Gdje ste vi otišli",
    firstWord: "Gdje ",
    secondWord: "ste",
    thirdWord: "vi",
    fourthWord: "otišli?",
    ENG_firstWord: "Where",
    ENG_secondWord: "have",
    ENG_thirdWord: "you",
    ENG_fourthword: "gone?",
    choices: ["had", "has", "having", "have"],
    correctAnswer: "have",
  },
  {
    id: 2,
    sentenceBosnian: "Jel sve uredu?",
    firstWord: "Jel",
    secondWord: "sve",
    thirdWord: "uredu?",
    fourthWord: "",
    ENG_firstWord: "Is",
    ENG_secondWord: "everything",
    ENG_thirdWord: "OK?",
    ENG_fourthword: "",
    choices: ["everything", "something", "anything", "nothing"],
    correctAnswer: "everything",
  },
  {
    id: 3,
    sentenceBosnian: "Uključi televiziju!",
    firstWord: "Uključi",
    secondWord: "televiziju!",
    thirdWord: "",
    fourthWord: "",
    ENG_firstWord: "Turn",
    ENG_secondWord: "the TV",
    ENG_thirdWord: "on!",
    ENG_fourthword: "",
    choices: ["the door", "the CV", "the microwave", "the TV"],
    correctAnswer: "the TV",
  },
  {
    id: 4,
    sentenceBosnian: "Taj datum mi odgovara.",
    firstWord: "Taj",
    secondWord: "datum",
    thirdWord: "mi",
    fourthWord: "odgovara.",
    ENG_firstWord: "That",
    ENG_secondWord: "date",
    ENG_thirdWord: "suits",
    ENG_fourthword: "me.",
    choices: ["afternoon", "dating", "date", "time"],
    correctAnswer: "date",
  },
  {
    id: 5,
    sentenceBosnian: "Ispričavam se",
    firstWord: "Ispričavam",
    secondWord: "se.",
    thirdWord: "",
    fourthWord: "",
    ENG_firstWord: "Excuse",
    ENG_secondWord: "me.",
    ENG_thirdWord: "",
    ENG_fourthword: "",
    choices: ["us.", "I.", "then.", "me."],
    correctAnswer: "me.",
  },
  {
    id: 6,
    sentenceBosnian: "Ta olovka je lijepa.",
    firstWord: "Ta",
    secondWord: "olovka",
    thirdWord: "je",
    fourthWord: "lijepa.",
    ENG_firstWord: "That",
    ENG_secondWord: "pencil",
    ENG_thirdWord: "is",
    ENG_fourthword: "nice.",
    choices: ["pen", "pencil", "quill", "pencils"],
    correctAnswer: "pencil",
  },
  {
    id: 7,
    sentenceBosnian: "Ja moram ići.",
    firstWord: "Ja",
    secondWord: "moram",
    thirdWord: "ići.",
    fourthWord: "",
    ENG_firstWord: "I",
    ENG_secondWord: "have",
    ENG_thirdWord: "to",
    ENG_fourthword: "go.",
    choices: ["have", "had", "has", "having"],
    correctAnswer: "have",
  },
  {
    id: 8,
    sentenceBosnian: "Moja mačka je bolesna.",
    firstWord: "Moja",
    secondWord: "mačka",
    thirdWord: "je",
    fourthWord: "bolesna.",
    ENG_firstWord: "My",
    ENG_secondWord: "cat",
    ENG_thirdWord: "is",
    ENG_fourthword: "sick.",
    choices: ["dog", "rat", "cat", "hamster"],
    correctAnswer: "cat",
  },
  {
    id: 9,
    sentenceBosnian: "Ja ću doći kasnije",
    firstWord: "Ja",
    secondWord: "ću",
    thirdWord: "doći",
    fourthWord: "kasnije.",
    ENG_firstWord: "I",
    ENG_secondWord: "will",
    ENG_thirdWord: "arrive",
    ENG_fourthword: "later",
    choices: ["was", "will", "would've", "should've"],
    correctAnswer: "will",
  },
];
